kind = "web"
previewPath = "/"
title = "NutriApp"
version = "1.0.0"
id = "artifacts/nutri-app"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22340

[services.development]
run = "pnpm --filter @workspace/nutri-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nutri-app", "run", "build" ]
serve = "static"
publicDir = "artifacts/nutri-app/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22340"
BASE_PATH = "/"
